### ISSUE TITLE
NGCBMUnitID required parameter for B1610

### ISSUE THREAD

**Issue by BenPortner** [MichaelKavanagh/elexon#2]
Hi @MichaelKavanagh !

I get a `TypeError: missing parameter NGCBMUnitID` when trying to call the B1610 API without this parameter specified. However, according to the official documentation this is not a required parameter.

Off topic:
Nice work on the wrapper! I'm trying to find a library to download Elexon data and came across your repo. I tried [pywind](https://github.com/zathras777/pywind) before, but it's heavily outdated. Out of curiosity: Do you know about [elexon api tool](https://github.com/GiorgioBalestrieri/elexon_api_tool)? I wonder what are the differences between your package and theirs.

Cheers!
Ben

**Comment by michaelkavanagh** [comment]
Hi Ben,

It looks like there is an error in Elexon's [documentation](https://www.elexon.co.uk/guidance-note/bmrs-api-data-push-user-guide/):

<img width="799" alt="Screenshot 2020-06-16 at 10 25 10" src="https://user-images.githubusercontent.com/1090536/84757253-d4134800-afbb-11ea-8b98-4b0c5adc974d.png">

The parameter you mention, `NGCBMUnitID` is in the sample Input URL but not in the field list below. The wrapper's list of methods and parameters is built from this, so this would explain the error.

I will contact Elexon and ask for clarification before committing a fix. How do you use this package? Install using pip?

I am aware of (and have reviewed) most open source Elexon BMRS wrappers out there, including the two you mentioned, and welcome collaboration.

Cheers,
Michael

**Comment by BenPortner** [comment]
Hi @MichaelKavanagh 

I really hope that it is not an error in their API. It is too comfortable downloading data for all units at once 😄  Yep, I installed using pip!

So, as a potential user I wonder: Why did you decide to build your own package? What will be the key differences?

**Comment by michaelkavanagh** [comment]
> I really hope that it is not an error in their API. It is too comfortable downloading data for all units at once 😄 

Likely not an error in their API, just their documentation. I am awaiting a response from Elexon.

> So, as a potential user I wonder: Why did you decide to build your own package? What will be the key differences?

The other packages did not fulfill my own needs, either they were stale, did not work, only worked for limited endpoints/reports, unnecessary dependencies etc. I require this for my day job, and it made more sense and was more efficient to build my own than try and fix these issues via pull requests. Of the top of my head, some of the key features of this package:

- OO
- Lightweight and minimalist: few dependencies, self documenting
- Generalisable: can use all endpoints (see [methods.py](https://github.com/MichaelKavanagh/elexon/blob/master/elexon/methods.py) and dynamic method creation in [elexon.py](https://github.com/MichaelKavanagh/elexon/blob/master/elexon/elexon.py)). Of course there might be bugs, I haven't tested them all, only when I need them.
- Extensible: I plan to add STOMP based "Data push service" support, [Pandas client](https://github.com/MichaelKavanagh/elexon/blob/master/elexon/elexon.py#L194), etc.
- Test coverage: WIP (as always 🙄)
- Not tangled in some larger project

**Comment by michaelkavanagh** [comment]
I received the following response, which is satisfactory enough for me. Fix incoming.

<img width="890" alt="Screenshot 2020-06-16 at 11 41 45" src="https://user-images.githubusercontent.com/1090536/84764978-70424c80-afc6-11ea-863f-73f187b8cf04.png">

NOTE: this report (B1610) does not work with the default API version 'v1'. You seem to need to use 'v2', which can be achieved by instantiating the ElexonRawClient class with `api_version = 'v2'`:

```python
api = ElexonRawClient('API_KEY', 'v2') 
```

**Comment by BenPortner** [comment]
That was a very quick answer! Thank you very much for the follow-ups and for your elaboration on the key features. I think elexon sounds very promising and I will keep following your updates! 😃

**Comment by michaelkavanagh** [comment]
Quick followup:

The [Elexon BMRS API documentation](https://www.elexon.co.uk/guidance-note/bmrs-api-data-push-user-guide/) has been updated to Version 3.1 (1 July 2020), with a correction to the section "5.1.22 B1610 – Actual Generation Output per Generation Unit" identified in this issue. It now includes the `NGCBMUnitID` parameter which is labelled as non-mandatory, so the commit made to close this issue was correct.

<img width="797" alt="Screenshot 2020-07-05 at 12 56 56" src="https://user-images.githubusercontent.com/1090536/86532099-1941e000-bebf-11ea-9595-345e3b9ca19a.png">

**Comment by BenPortner** [comment]
Hi @MichaelKavanagh,

thanks for the follow-up! That was a quick fix 😃 Thanks for your effort!

Ben
